server:
  port: 8761

spring:
  profiles:
    active: local

  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # 유레카 서버에 서비스 등록
    fetch-registry: false  # 레지스트리 정보를 로컬에 캐싱
